<?php

namespace App\Filament\App\Pages;

use App\Models\Country;
use Filament\Pages\Page;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\ImageColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\HtmlString;

class CountryPage extends Page implements HasTable
{
    use InteractsWithTable;
    protected static string | \BackedEnum | null $navigationIcon = Heroicon::GlobeAlt;

    protected  string $view = 'filament.app.pages.country-page';
    protected ?string $heading='';
    protected static ?int $navigationSort=9;
    protected static ?string $navigationLabel='الدول';
    public static function getNavigationBadge(): ?string
    {
        return app()->getLocale(); // TODO: Change the autogenerated stub
    }
    public function mount(): void
    {

        if (session()->has('lang_code')) {

            app()->setLocale(session()->get('lang_code'));
        }

    }

    public function table(Table $table): Table
    {
        return $table
            ->query(function () {
                return Country::where('name','!=',null);
            })

            ->paginated(false)
            ->queryStringIdentifier('countries')
            ->defaultSort('victim_count','desc')
            ->striped()
            //->extraAttributes('class'=>'fi')
            ->columns([
                TextColumn::make('ت')
                    ->rowIndex(),
                TextColumn::make('name')
                    ->color('blue')
                    ->label('الدولة'),
                TextColumn::make('victim_count')
                    ->color('warning')
                    ->label('العدد')
                    ->counts('Victim'),
                ImageColumn::make('image')
                    ->label(' ')
                    ->circular()
            ]);
    }
}
