<?php

namespace App\Filament\Resources\Victims\Pages;

use App\Filament\Resources\Victims\VictimResource;
use App\Models\Victim;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class CreateVictim extends CreateRecord
{
    protected static string $resource = VictimResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        if ($data['mother_id']) Victim::find($data['mother_id'])->update(['is_mother'=>1]);
        if ($data['father_id']) Victim::find($data['father_id'])->update(['is_father'=>1]);

        $data['FullName']=$data['Name1'].' '.$data['Name2'].' '.$data['Name3'].' '.$data['Name4'];
        $name = [
            'ar' => $data['FullName'],
            'en' => Str::ascii($data['FullName'], 'ar')
        ];
        $data['FullNameJs']=$name;

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

}
