<?php

namespace App\Filament\Resources\Victims\Pages;

use App\Filament\Resources\Victims\VictimResource;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class EditVictim extends EditRecord
{
    protected static string $resource = VictimResource::class;

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['FullName']=$data['Name1'].' '.$data['Name2'].' '.$data['Name3'].' '.$data['Name4'];
        $name = [
            'ar' => $data['FullName'],
            'en' => Str::ascii($data['FullName'], 'ar')
        ];
        $data['FullNameJs']=$name;

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
