<?php

namespace App\Filament\Resources\Victims\Pages;

use App\Filament\Resources\Victims\VictimResource;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Stichoza\GoogleTranslate\GoogleTranslate;

class EditVictim extends EditRecord
{
    protected static string $resource = VictimResource::class;

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['FullName']=$data['Name1'].' '.$data['Name2'].' '.$data['Name3'].' '.$data['Name4'];
        $name = [
            'ar' => $data['FullName'],
            'en' => Str::ascii($data['FullName'], 'ar')
        ];
        $data['FullNameJs']=$name;

        if ($data['notes']) {
            $tr = new GoogleTranslate(); // Translates to 'en' from auto-detected language by default
            $tr->setSource('ar');
            $tr->setTarget('en');
            $notes = [
                'ar' => $data['notes'],
                'en' => $tr->translate($data['notes'])
            ];
            $data['notesJs'] = $notes;
        }

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
