<?php

namespace App\Filament\Clusters\Aljabel\Resources\Aljabels\Pages;

use App\Filament\Clusters\Aljabel\Resources\Aljabels\AljabelResource;
use Filament\Resources\Pages\CreateRecord;

class CreateAljabel extends CreateRecord
{
    protected static string $resource = AljabelResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {


        $name =  $data['Name1'].' '.$data['Name2'].' '.$data['Name3'].' '.$data['Name4'];

        $data['FullName']=$name;

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
