<?php

namespace App\Filament\Clusters\Aljabel\Resources\Aljabels\Pages;

use App\Filament\Clusters\Aljabel\Resources\Aljabels\AljabelResource;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Log;


class EditAljabel extends EditRecord
{
    protected static string $resource = AljabelResource::class;

    protected function getHeaderActions(): array
    {
        return [
            ViewAction::make(),
            DeleteAction::make(),
        ];
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {


        $name = [
          'ar'=> $data['Name1']['ar'].' '.$data['Name2']['ar'].' '.$data['Name3']['ar'].' '.$data['Name4']['ar'],

        ] ;



        $data['FullName']=$name;
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
