<?php

namespace App\Filament\Clusters\Aljabel\Resources\Aljabels\Pages;

use App\Filament\Clusters\Aljabel\Resources\Aljabels\AljabelResource;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;

class EditAljabel extends EditRecord
{
    protected static string $resource = AljabelResource::class;

    protected function getHeaderActions(): array
    {
        return [
            ViewAction::make(),
            DeleteAction::make(),
        ];
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
        $name =  $data['Name1'].' '.$data['Name2'].' '.$data['Name3'].' '.$data['Name4'];

        $data['FullName']=$name;
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
