<?php

namespace App\Filament\Resources\Familyshows\Pages;

use App\Filament\Resources\Familyshows\FamilyshowResource;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Str;

class EditFamilyshow extends EditRecord
{
    protected static string $resource = FamilyshowResource::class;
    protected function mutateFormDataBeforeSave(array $data): array
    {

        $name = [
            'ar' => $data['name'],
            'en' => Str::ascii($data['name'], 'ar')
        ];
        $data['nameJs']=$name;

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

}
