<?php

namespace App\Filament\Clusters\Translations\Resources\Familyshows\Pages;

use App\Filament\Clusters\Translations\Resources\Familyshows\FamilyshowResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Str;

class CreateFamilyshow extends CreateRecord
{
    protected static string $resource = FamilyshowResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {


        $name = [
            'ar' => $data['name'],
            'en' => Str::ascii($data['name'], 'ar')
        ];
        $data['nameJs']=$name;

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

}
